apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority: /root/ca.crt
    server: https://192.168.99.100:8443
  name: cluster1

contexts:
- context:
    cluster: cluster1
    user: kubectl

users:
- name: kubectl
  user:
    client-certificate: /root/client.crt
    client-key: /root/client.key